---
title: "TryingStuffWithSpotifyData"
author: "Gabe Cederberg"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)
library(lubridate)
library(ggrepel)
library(dplyr)
options(scipen = 999)
```

```{r, echo = FALSE, message = FALSE}
# Loading Data

x <- read_csv("SpotifyData.csv",
  col_types = cols(
    Date = col_date(format = "%m/%d/%y"))) %>% 
  clean_names() %>% 
  select(date,
         artist, 
         title = "song_title",
         mins = "minutes_listened",
         time = "timeof_day",
         weekday = "dayofthe_week",
         month) %>% 
  separate(artist, "artist",",")

# Most listened to songs by an artist

top_songs <- x %>% 
  group_by(artist, title) %>% 
    summarize(total_mins = sum(mins)) %>% 
    top_n(n=1) %>% 
    arrange(desc(total_mins))

  
  
# top_songs <- x %>% 
#   group_by(artist, title) %>% 
#   summarize(total_mins = sum(mins)) %>% 
#   arrange(desc(total_mins))


top_artists <- x %>% 
  group_by(artist, title) %>% 
  summarize(total_mins = sum(mins)) %>% 
  ungroup() %>% 
  group_by(artist) %>% 
  summarize(big_artists = sum(total_mins))

top_artists

both <- top_songs %>% left_join(top_artists, by = "artist") %>% 
  filter(total_mins > 165 | big_artists > 1100) %>% 
  filter(artist != "Why Is This Happening? with Chris Hayes" &
           artist != "Pod Save America" &
            artist != "Pod Save the World")

both

both %>% ggplot(aes(big_artists, total_mins, label = title, size = big_artists, color = artist)) + 
  geom_point() +
  geom_label_repel(hjust=1, vjust=0.5, size = 2, alpha = 0.8) +
  theme_classic() +
  labs(
    title = "Top songs that Gabe listened to in 2019 from each artist",
  #  subtitle = "Drake dominates the listening",
       y = "Minutes Listened to Individual Songs",
       x = "Minutes Listened to Each Artist",
    color = "",
    caption = "Data from Jan. 5 2019 to Jan. 5 2020") +
      theme(legend.position = "none") 
 # scale_color_viridis_d("plasma")

# ggsave("Listeningsummary2019.jpg", plot = last_plot(), width = 7, height = 5)
```


```{r, echo = FALSE, message = FALSE}
drake <- x %>% 
  filter(artist == "Juice WRLD") %>% 
  group_by(title) %>%
  summarize(total_listening = sum(mins)) %>% 
  arrange(desc(total_listening)) 
drake

drake %>% 
  ggplot(aes(date, color = title)) +
  geom_density()


# Most listened to artists

x %>% group_by(artist) %>% 
  summarize(total_mins = sum(mins)) %>% 
  arrange(desc(total_mins))


x %>% 
  filter(artist == "Juice WRLD") %>% 
  filter(title == c("Feeling,", 
                    "Armed And Dangerous,",
                    "Robbery,",
                    "Fast,",
                    "Hear Me Calling,")) %>% 
  group_by(date, title) %>% 
  summarize(total_day = sum(mins)) %>% 
  ggplot(aes(date, color = title)) +
  geom_density()


# Compare listening trends among artists

a <- x %>% 
  filter(artist == "Drake" |
           artist == "Sam Cooke" |
           artist == "Post Malone" |
           artist == "Tyga" |
           artist == "G-Eazy" |
           artist == "Young Thug" |
           artist == "YNW Melly" |
           artist == "The Weeknd") %>% 
  group_by(artist, date) %>% 
  summarize(totalmins = sum(mins))

ggplot(a, aes(date, color = artist)) +
      geom_density() 


#a <- x %>% 
#    with_tz(TimeofDay, "America/New_York")
```


```{r}
#Trying to Visualize Minutes Listened by Time of Day

daytime <- x %>% group_by(time) %>% 
  filter(date > "2019-10-01" &
           date < "2019-11-01") %>% 
  summarize(total = sum(mins)) %>% 
  separate(time, c("hour", "minute", "second")) %>% 
  group_by(hour)


ggplot(daytime, aes(hour, total)) +
  geom_col()

```

```{r}
# Minutes listened to an artist by day of the week

drake_days <- x %>% 
  filter(artist == "Sergei Rachmaninoff") %>% 
  group_by(weekday) %>% 
  summarize(total_mins = sum(mins))

ggplot(drake_days, aes(weekday, total_mins)) +
  geom_col()
```

```{r}
x %>% 
  filter(title == "Psycho (feat. Ty Dolla $ign),") %>% 
  group_by(date) %>% 
  summarize(total_daily_listen = sum(mins)) %>% 
  ggplot(aes(date, total_daily_listen)) +
  geom_col()

x %>% 
  filter(title == "Plastic Bag,") %>% 
  group_by(date) %>% 
  summarize(total_daily_listen = sum(mins),
            total_daily_count = n()) %>% 
  ggplot(aes(date)) +
  geom_col(aes(y = total_daily_listen)) +
  geom_line(aes(y = total_daily_count)) +
  scale_y_continuous(
    
    # Features of the first axis
    name = "Minutes Listened",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*1, name="Times Listened")) +
    theme_classic() +
  labs(
    title = "Gabe's Listening to Plastic Bag by Drake and Future in 2019",
  #  subtitle = "Drake dominates the listening",
    #   y = "Minutes Listened to Individual Songs",
   #    x = "Minutes Listened to Each Artist",
    caption = "Data from Jan. 5 2019 to Jan. 5 2020")


ggsave("PlasticBagNumbers.jpg", plot = last_plot(), width = 7, height = 5)

``` 


```{r}
#Trying to Visualize Minutes Listened by Time of Day, filtering for just EST
# z <- x %>% 
#   group_by(TimeofDay) %>% 
#   filter(Date >= "2019-09-01" & Date <= "2019-12-01") %>% 
#   mutate(totalMinutesFilter = sum(MinutesListened))
# 
# z
# 
# ggplot(z, aes(TimeofDay, totalMinutesFilter)) + geom_col()
```

